# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: AnSwEr's Blog
subtitle:
description: Stay true to yourself,Stay gold.
author: AnSwEr(Weijie Yuan)
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://answerywj.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
    type: git
    repo: git@github.com:AnSwErYWJ/AnSwErYWJ.github.io.git
    branch: master
    message: 'update website:{{now("YYYY-MM-DD HH:mm:ss")}}'

# avatar
avatar: http://o9zpdspb3.bkt.clouddn.com/avatar.png
    
# duoshuo
#duoshuo_shortname: answerywj

#baidu analytics
baidu_analytics: e12c3989e0050ebd884435d0e1f1bed4

# JiaThis 分享服务
jiathis: true

search:
    path: search.xml
    field: post

# 多说热评文章 true 或者 false
#duoshuo_hotartical: true

feed:
    type: atom
    path: atom.xml
    limit: 20
    hub:

